from typing import Any, Dict

from services.report_template import (
    DEFAULT_SOURCE,
    ElementType,
    ReportElement,
    element_to_dict,
    REPORT_TEMPLATE,
)


def enrich_academic_metadata(result: dict) -> dict:
    """
    Map legacy phase output elements (report_tables, report_figures) to the new
    format using ReportElement dicts, preserving the original IDs and titles
    generated by each phase script.
    """
    if not isinstance(result, dict):
        return result

    elements = result.get("elements", [])
    new_elements = []

    for table in (result.get("report_tables") or []):
        if not isinstance(table, dict):
            continue
            
        el_dict = {
            "type": ElementType.DATA_TABLE.value,
            "id": str(table.get("id")),
            "title": table.get("title", ""),
            "caption": f"Tabla {table.get('id')}. {table.get('title')}.",
            "source": table.get("source") or DEFAULT_SOURCE,
            "columns": table.get("columns", []),
            "rows": table.get("rows", []),
        }
        if isinstance(el_dict["rows"], list):
            el_dict["sample_size"] = len(el_dict["rows"])
            
        new_elements.append(el_dict)

    for figure in (result.get("report_figures") or []):
        if not isinstance(figure, dict):
            continue

        el_dict = {
            "type": figure.get("type", ElementType.CHART.value),
            "id": str(figure.get("id")),
            "title": figure.get("title", ""),
            "caption": f"Figura {figure.get('id')}. {figure.get('title')}.",
            "source": figure.get("source") or DEFAULT_SOURCE,
        }
        for key in ["kind", "url", "dataKey", "dataKeys", "categoryKey", "rows", "columns", "description", "content", "method", "notes", "baseline"]:
            if key in figure:
                el_dict[key] = figure[key]
                
        new_elements.append(el_dict)

    result["elements"] = elements + new_elements
    
    # Remove legacy fields
    if "report_tables" in result:
        del result["report_tables"]
    if "report_figures" in result:
        del result["report_figures"]

    return result
