# Constants for network analysis

THRESHOLD_PATH_INFLATION = 20.0
QOE_LATENCY_IMPERCEPTIBLE = 50.0
QOE_LATENCY_ACCEPTABLE = 150.0
QOE_LATENCY_DEGRADATION = 200.0

# Classification bands
BAND_LOCAL = 15.0
BAND_REGIONAL = 40.0
BAND_INTERNATIONAL = 80.0
